### ISSUE TITLE
Playground not working

### ISSUE THREAD

**Issue by Sjors** [CryptoCoinSwift/SHA256-Swift#2]
I created a Mac playground to demonstrate this framework. I have been successful at getting some of the other CryptoCoinSwift frameworks to work in a playground, but not this one.

The framework uses a module.map file to access CC_SHA256, as described [here](https://devforums.apple.com/message/1009274#1009274). I wrote an [XCTestCase](https://github.com/CryptoCoinSwift/SHA256-Swift/blob/master/SHA256Tests.swift) which successfully loads my framework and performs a hash. I'm also able to import and use the framework in other frameworks.

When I try import SHA256Mac into a playground it says "Missing required module 'CommonCrypto".
When I try import CommonCrypto it says: No such module "CommonCrypto".

I set the current scheme to the Mac framework. Defines Module is set to yes.

See also [my post](https://devforums.apple.com/message/1020831#1020831) on the Apple Developer Forum.

**Comment by seabass223** [comment]
I second this. it works!
